packages:
  - 'clients/typescript'
  - 'e2e/satellite_client'
  - 'examples/starter'
  - 'generator'
  - 'components/electric'
  - 'examples/tauri-postgres'
  - 'examples/tauri-postgres-from-wa-sqlite'
  - 'examples/web-wa-sqlite'
