version: "3.8"
name: "todomvc"

configs:
  postgres_config:
    file: "./postgres/postgres.conf"

volumes:
  pg_data:

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: todomvc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg_password
    command:
      - -c
      - config_file=/etc/postgresql.conf
    configs:
      - source: postgres_config
        target: /etc/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 5632:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
